exports.seed = (knex, Promise) => {
  return Promise.all([
    knex('knapsak_items').insert({ knapsak_id: 1, item_id: 1, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 1, item_id: 2, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 1, item_id: 3, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 1, item_id: 4, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 1, item_id: 5, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 1, item_id: 6, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 1, item_id: 7, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 1, item_id: 8, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 1, item_id: 9, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 1, item_id: 10, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 1, item_id: 11, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 1, item_id: 12, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 1, item_id: 13, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 2, item_id: 1, quantity: 2 }),
    knex('knapsak_items').insert({ knapsak_id: 2, item_id: 2, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 2, item_id: 3, quantity: 2 }),
    knex('knapsak_items').insert({ knapsak_id: 2, item_id: 4, quantity: 3 }),
    knex('knapsak_items').insert({ knapsak_id: 2, item_id: 5, quantity: 1 }),
    knex('knapsak_items').insert({ knapsak_id: 2, item_id: 6, quantity: 1 }),
    knex('knapsak_items').insert({ knapsak_id: 2, item_id: 7, quantity: 1 }),
    knex('knapsak_items').insert({ knapsak_id: 2, item_id: 8, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 2, item_id: 9, quantity: 1 }),
    knex('knapsak_items').insert({ knapsak_id: 2, item_id: 10, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 2, item_id: 11, quantity: 1 }),
    knex('knapsak_items').insert({ knapsak_id: 2, item_id: 12, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 2, item_id: 13, quantity: 1 }),
    knex('knapsak_items').insert({ knapsak_id: 3, item_id: 1, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 3, item_id: 2, quantity: 5 }),
    knex('knapsak_items').insert({ knapsak_id: 3, item_id: 3, quantity: 1 }),
    knex('knapsak_items').insert({ knapsak_id: 3, item_id: 4, quantity: 3 }),
    knex('knapsak_items').insert({ knapsak_id: 3, item_id: 5, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 3, item_id: 6, quantity: 1 }),
    knex('knapsak_items').insert({ knapsak_id: 3, item_id: 7, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 3, item_id: 8, quantity: 1 }),
    knex('knapsak_items').insert({ knapsak_id: 3, item_id: 9, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 3, item_id: 10, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 3, item_id: 11, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 3, item_id: 12, quantity: 1 }),
    knex('knapsak_items').insert({ knapsak_id: 3, item_id: 13, quantity: 1 }),        knex('knapsak_items').insert({ knapsak_id: 4, item_id: 1, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 4, item_id: 2, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 4, item_id: 3, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 4, item_id: 4, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 4, item_id: 5, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 4, item_id: 6, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 4, item_id: 7, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 4, item_id: 8, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 4, item_id: 9, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 4, item_id: 10, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 4, item_id: 11, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 4, item_id: 12, quantity: 0 }),
    knex('knapsak_items').insert({ knapsak_id: 4, item_id: 13, quantity: 0 }),
  ])
}
